# Generated by Django 4.1.6 on 2023-03-10 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_paymentmethod_bank_account_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="paymentmethod",
            table="payment_methods",
        ),
    ]
