# Generated by Django 4.1.6 on 2023-03-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChargingStation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=60)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9, verbose_name="위도")),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9, verbose_name="경도")),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Charger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(choices=[("fast", "급속"), ("slow", "완속")], max_length=20)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "charging_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chargers",
                        to="charging.chargingstation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
