# Generated by Django 4.1.6 on 2023-03-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingstation",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
