# Generated by Django 4.1.6 on 2023-03-10 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(choices=[("card", "신용카드"), ("bank_transfer", "계좌이체")], max_length=20)),
                ("card_number", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kookmin", "KB국민은행"),
                            ("shinhan", "신한은행"),
                            ("woori", "우리은행"),
                            ("hana", "KEB하나은행"),
                            ("nh", "농협"),
                            ("city", "시티은행"),
                            ("kakao", "카카오뱅크"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("bank_account", models.CharField(blank=True, max_length=50, null=True, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_methods",
            },
        ),
    ]
